config/routes.rb
Rails.application.routes.draw do
  resources :items, only: %i(index show) do
    collection do
      get :recommended
      get :uncategorized
    end
  end

  root 'portal#show'

  resources :categories, only: %i(show) do
    resources :items, only: %i(index)
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = get_items
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  def recommended
    @items = Item.where(recommended: true)
    render action: :index
  end

  def uncategorized
    @items = Item.where(category_id: nil)
    render action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_items 
      if params[:category_id]
        #Category.find(params[:category_id]).items
        Item.where(category_id: params[:category_id])
      else
        Item.all
      end
    end
end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  def show
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
%h1 Listing items
%ul.items
  - @items.each do |item|
    %li.item
      %h2
        - if item.recommended?
          %span.recommened おすすめ
        = link_to item.name, item
      %p= item.description

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item.name
%p
  = image_tag(@item.image_url)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EcMine
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/portal/show.html.haml
%p#notice= notice

%ul
  - @categories.each do |category|
    %li= link_to category.name, category_items_path(category)